[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ["pgvector.asyncpg"]
ignore_missing_imports = true

[tool.pytest.ini_options]
markers = [
    "postgres",
]
